apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      automountServiceAccountToken: false
      containers:
      - name: keycloak
        image: keycloak:dev
        imagePullPolicy: IfNotPresent
        args: ["start", "--optimized"]
        env:
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: "tmpadmin"
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: "admin"
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL
          value: "jdbc:postgresql://host.minikube.internal:5432/MapMarkerDb?currentSchema=keycloak"
        - name: KC_DB_USERNAME
          value: "keycloak"
        - name: KC_DB_PASSWORD
          value: "keycloak"
        - name: KC_HOSTNAME
          value: "http://localhost:50594/login"
        - name: KC_HOSTNAME_ADMIN
          value: "http://127.0.0.1:50594/login"
        - name: KC_HOSTNAME_STRICT
          value: "true"
        - name: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
          value: "false"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_LOG
          value: "console,file"
        - name: KC_LOG_CONSOLE_LEVEL
          value: "error"
        - name: KC_LOG_FILE
          value: "/opt/keycloak/log/server.log"
        - name: KC_LOG_ASYNC
          value: "true"
        - name: KC_CACHE
          value: "ispn"
        ports:
        - name: http
          containerPort: 8080
        - name: management
          containerPort: 9000
        readinessProbe:
          httpGet:
            path: /keycloak/health/ready
            port: management
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /keycloak/health/live
            port: management
          initialDelaySeconds: 90
          periodSeconds: 10
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "1000m"
            ephemeral-storage: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: management
    port: 9000
    targetPort: 9000
  selector:
    app: keycloak
